### ISSUE TITLE
Add Veteran Balance Patch checkbox by Humble/Skylegend/xme

### ISSUE THREAD

**Issue by Metadorius** [CnCNet/cncnet-ts-client-package#10]
Would just append the following INI to the map:

https://github.com/HumbleTS/Balance-Veteran-Patch/blob/master/code

**Comment by Metadorius** [comment]
More updated one apparently?

https://cdn.discordapp.com/attachments/1043920203106496564/1260548295726596116/Vet.Bal.ini?ex=668fb895&is=668e6715&hm=1a8220d04c4c1fc0f4f6b1c15c6f875fe5ef6a382f320a972ed4bb1f0661970b&

**Comment by GrantBartlett** [comment]
Who's this assigned to @Metadorius @Bittah ? Is this required for the milestone?

**Comment by Metadorius** [comment]
I was only helping with tracking, it should not be hard to do that for @Bittah. I would say it is required because vet patch is popular among TS players.

**Comment by Bittah** [comment]
Added in https://github.com/CnCNet/cncnet-ts-client-package/commit/7af196567b34322a57b4c8cf2da211f9d8c51b98.
