### ISSUE TITLE
TS CLient uses wrong key name for selecting one less unit

### ISSUE THREAD

**Issue by Prometheus3375** [CnCNet/cncnet-ts-client-package#21]
When setting Select One Unit Less hotkey via TS Client, it adds `SelectOneUnitLess` to `Keyboard.ini`. But this is incorrect. TS uses `SelectOneLess` for this hotkey, this can be checked by setting this hotkey via game itself.

When changing hotkeys via game, it reads `Keyboard.ini` and removes any incorrect names, and for TS `SelectOneUnitLess` is incorrect. This makes TS Client think the hotkey is unset. If a person opens hotkey configuration in TS client and saves (even without edits), this also removes any incorrect names, but for TS Client `SelectOneLess` is incorrect.

Also, cheer is not in the game as far as I know, the game does not have in its settings.

**Comment by Prometheus3375** [comment]
Here I think it should be changed:

https://github.com/CnCNet/cncnet-ts-client-package/blob/e8b141f9abd44049b0661dba1dd4065500212a67/Resources/KeyboardCommands.ini#L25-L29

https://github.com/CnCNet/cncnet-ts-client-package/blob/e8b141f9abd44049b0661dba1dd4065500212a67/Resources/KeyboardCommands.ini#L325-L329

**Comment by Bittah** [comment]
Fixed by https://github.com/CnCNet/cncnet-ts-client-package/commit/4890fa78b39dcf97c9cfc3e105ab0a572a5ee48a.
