### ISSUE TITLE
Unable to enter LAN lobby in Extra menu

### ISSUE THREAD

**Issue by MahBoiDeveloper** [CnCNet/cncnet-ts-client-package#22]
Demonstration:

https://github.com/user-attachments/assets/14c7cbfc-ab7f-4215-a182-b7ba30d86516

Broken at https://github.com/CnCNet/cncnet-ts-client-package/commit/ec771d17e313d9b38ce02d55571ad8ad5af45360 commit.

**Comment by Bittah** [comment]
Fixed by https://github.com/CnCNet/cncnet-ts-client-package/commit/4da268d5b5969ead2e5df8f38feed6e41ffc101d.
