### ISSUE TITLE
Untextured cell in GDI 10b mission

### ISSUE THREAD

**Issue by Prometheus3375** [CnCNet/cncnet-ts-client-package#5]
@CCHyper asked to move [issue](https://github.com/CnCNet/ts-patches/issues/100) from TS patches to this repo.

Untextured cell is situated in the right bottom corner.

![image](https://github.com/CnCNet/cncnet-ts-client-package/assets/35541026/0f4c63e9-48ba-4e83-89d0-ff29f6f58cfb)
![image](https://github.com/CnCNet/cncnet-ts-client-package/assets/35541026/e0e6633a-73a2-4d82-905e-ab9482b78bd8)

**Comment by Bittah** [comment]
Fixed in bf4511d757c0693bbcca91e703b2bd89852b79d7.
